name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: second_test
        type: choice
        options:
          - first_test
          - second_test
          - all

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable

      - name: Install dependencies
        run: pip install -r requirements.txt

     # - name: Download all workflow run artifacts
     #   uses: actions/download-artifact@v3

      - name: first_test
        if: "github.event.inputs.deployment_target == 'first_test'"
        run: pytest tests/test_button.py::test_button_exist --alluredir=allure-results
        continue-on-error: true

      - name: second_test
        if: "github.event.inputs.deployment_target == 'second_test'"
        run: pytest tests/test_button.py::test_button_exist_2 --alluredir=allure-results
        continue-on-error: true

      - name: all
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest --alluredir=allure-results
        continue-on-error: true

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build Allure report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.G_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          destination_dir: .